export class CapacityContractError extends Error { status: number; code: string; constructor(status: number, message: string, code?: string); }
export const GPU_LISTING_STATUSES: Set<string>;
export const GPU_ALLOCATION_MODES: Set<string>;
export const GPU_CONNECTION_MODES: Set<string>;
export const PROVIDER_NODE_STATUSES: Set<string>;
export const PROVIDER_NODE_HEALTH_STATUSES: Set<string>;
export const RESERVATION_STATUSES: Set<string>;
export const TERMINAL_RESERVATION_STATUSES: Set<string>;
export const EARNING_STATUSES: Set<string>;
export const PAYOUT_STATUSES: Set<string>;
export const PAYOUT_PROFILE_STATUSES: Set<string>;
export const PAYOUT_METHODS: Set<string>;
export function nowIso(now?: Date | string | number): string;
export function requireString(value: unknown, fieldName: string, options?: Record<string, unknown>): string;
export function optionalString(value: unknown, fieldName: string, options?: Record<string, unknown>): string | undefined;
export function requireInteger(value: unknown, fieldName: string, options?: Record<string, unknown>): number;
export function requireNumber(value: unknown, fieldName: string, options?: Record<string, unknown>): number;
export function optionalUrl(value: unknown, fieldName: string): string | undefined;
export function normalizeCurrency(value?: unknown): string;
export function roundMoney(value: number): number;
export function calculateEffectiveAvailableGpuCount(gpuCount: number, reportedAvailableGpuCount: number, reservedGpuCount: number): number;
export function validateProviderNodeSubmission(input: any, identity: any, options?: any): any;
export function sanitizeProviderNode(node: any): any;
export function applyProviderNodeHeartbeat(node: any, input?: any, options?: any): any;
export function validateGpuCapacitySubmission(input: any, identity: any, options?: any): any;
export function isHeartbeatFresh(record: any, maximumAgeSeconds?: number, now?: Date): boolean;
export function createReservation(input: any, listing: any, node: any, buyer: any, identity: any, options?: any): any;
export function transitionReservation(reservation: any, action: string, input?: any, options?: any): any;
export function applyUsageReport(reservation: any, input: any, options?: any): any;
export function createEarning(reservation: any, identity: any, options?: any): any;
export function materializeEarningStatus(earning: any, options?: any): any;
export function summarizeEarnings(earnings: any[], options?: any): any;
export function validatePayoutProfile(input: any, ownerId: string, existing?: any, options?: any): any;
export function createPayout(input: any, profile: any, availableEarnings: any[], identity: any, options?: any): any;
export function transitionPayout(payout: any, action: string, input?: any, options?: any): any;
